from __future__ import annotations

from datetime import datetime, timezone
from enum import StrEnum
from typing import Any
from uuid import UUID, uuid4

from sqlalchemy import JSON, Column
from sqlmodel import DateTime, Field, SQLModel


class TaskStatus(StrEnum):
    """Canonical task lifecycle states visible to API, worker, and web polling."""

    QUEUED = "queued"
    PARSING = "parsing"
    UNDERSTANDING = "understanding"
    RETRIEVING = "retrieving"
    GENERATING = "generating"
    REVIEW_PENDING = "review_pending"
    REVIEWING = "reviewing"
    APPROVED = "approved"
    EXPORTING = "exporting"
    COMPLETED = "completed"
    FAILED = "failed"
    REJECTED = "rejected"


class Task(SQLModel, table=True):
    """Primary task record for the async workflow."""

    id: UUID = Field(
        default_factory=uuid4,
        primary_key=True,
        description="Stable task identifier returned to the client.",
    )
    input_type: str = Field(
        index=True,
        description="Task input type such as text, url, or file.",
    )
    content: str = Field(
        description="Raw task payload, URL, or stored file path.",
    )
    knowledge_domain: str | None = Field(
        default=None,
        index=True,
        description="Optional knowledge-domain scope used to constrain retrieval to the intended business area.",
    )
    status: TaskStatus = Field(
        default=TaskStatus.QUEUED,
        index=True,
        description="Current async workflow status.",
    )
    current_stage: str = Field(
        default=TaskStatus.QUEUED,
        description="Current processing stage for status display and audit.",
    )
    error_message: str | None = Field(
        default=None,
        description="Last failure reason when the workflow enters failed state.",
    )
    understanding: dict[str, Any] | None = Field(
        default=None,
        sa_column=Column(JSON, nullable=True),
        description="Structured understanding output generated by the pipeline.",
    )
    retrieval_hits: list[dict[str, Any]] = Field(
        default_factory=list,
        sa_column=Column(JSON, nullable=False),
        description="RAG retrieval hits returned for review and attribution.",
    )
    workflow_result: dict[str, Any] | None = Field(
        default=None,
        sa_column=Column(JSON, nullable=True),
        description="Structured workflow output shown before human review.",
    )
    review: dict[str, Any] | None = Field(
        default=None,
        sa_column=Column(JSON, nullable=True),
        description="Reviewer edits and decision metadata that remain mutable until approval.",
    )
    approved_snapshot: dict[str, Any] | None = Field(
        default=None,
        sa_column=Column(JSON, nullable=True),
        description="Canonical reviewed snapshot that downstream export must consume instead of mutable review fields.",
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        sa_column=Column(DateTime(timezone=True), nullable=False),
        description="Creation timestamp in UTC.",
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        sa_column=Column(DateTime(timezone=True), nullable=False),
        description="Last update timestamp in UTC.",
    )
