export type TaskStatus =
  | "queued"
  | "parsing"
  | "understanding"
  | "retrieving"
  | "generating"
  | "review_pending"
  | "reviewing"
  | "approved"
  | "exporting"
  | "completed"
  | "failed"
  | "rejected";

export type TaskInputType = "text" | "file" | "url";

export type StatusTone = "neutral" | "info" | "warning" | "success" | "danger";

export interface TaskStatusMeta {
  /** Human readable status label used in task list and detail headers. */
  label: string;
  tone: StatusTone;
  description: string;
  isActive: boolean;
}

export interface UnderstandingResult {
  /** Reviewer-facing short summary for the parsed source input. */
  summary: string;
  /** Audiences inferred by the backend before generation starts. */
  audience: string[];
  /** Key points the pipeline wants the reviewer to keep in view. */
  key_points: string[];
  /** Risk flags the pipeline wants reviewers to inspect before approval. */
  risk_points: string[];
  /** Items that still need manual confirmation. */
  uncertain_items: string[];
  /** Input quality markers generated during parsing. */
  input_quality: {
    source_kind: string;
    quality_flags: string[];
    extracted_length: number;
    metadata?: {
      title?: string;
      extractor?: string;
      [key: string]: unknown;
    };
  };
}

export interface ApiRetrievalHit {
  /** Stable backend source identifier used for visible attribution. */
  source_id: string;
  /** Human-readable source title. */
  title: string;
  /** Supporting excerpt returned by retrieval. */
  snippet: string;
  /** Why this source was chosen for the task. */
  reason: string;
}

export interface ApiWorkflowResult {
  /** Draft content generated by the first async slice. */
  draft: string;
  /** Notes the reviewer should inspect before approving later slices. */
  review_notes: string[];
  /** Questions still left open for human confirmation. */
  open_questions: string[];
  /** Evidence items the generated result claims to rely on. */
  evidence_used: { source_id: string; title: string }[];
  /** Uncertainties carried through to review. */
  uncertainties: string[];
  /** Manual checks still expected from a reviewer. */
  manual_checks: string[];
  /** Summary of the context package assembled for generation. */
  context_summary: {
    selected_hit_count: number;
    context_sections: string[];
  };
  /** Human-readable trace of major pipeline decisions. */
  processing_trace: string[];
}

export interface ApiReviewSnapshot {
  /** Current human review decision state. */
  decision: "in_review" | "approved" | "rejected";
  /** Reviewer note explaining the current action. */
  reviewer_note?: string | null;
  /** Reason recorded when the task is rejected. */
  rejection_reason?: string | null;
  /** Explicit items the reviewer chose not to adopt. */
  not_adopted_items: string[];
  /** Reviewer replacement for understanding, when present. */
  edited_understanding?: UnderstandingResult | null;
  /** Reviewer replacement for retrieval hits, when present. */
  edited_retrieval_hits: ApiRetrievalHit[];
  /** Reviewer replacement for workflow result, when present. */
  edited_workflow_result?: ApiWorkflowResult | null;
}

export interface ApiApprovedSnapshot {
  understanding?: UnderstandingResult | null;
  retrieval_hits: ApiRetrievalHit[];
  workflow_result?: ApiWorkflowResult | null;
}

/**
 * Raw task payload returned by the current backend slice.
 * The UI keeps this shape explicit so future backend evolution is easy to spot.
 */
export interface ApiTaskRecord {
  id: string;
  input_type: TaskInputType;
  content: string;
  knowledge_domain?: string | null;
  status: TaskStatus;
  current_stage: string;
  error_message: string | null;
  understanding?: UnderstandingResult | null;
  retrieval_hits: ApiRetrievalHit[];
  workflow_result?: ApiWorkflowResult | null;
  review?: ApiReviewSnapshot | null;
  approved_snapshot?: ApiApprovedSnapshot | null;
  created_at: string;
  updated_at: string;
}

export interface TaskSummary {
  summary?: string | null;
  audience?: string | null;
  key_points?: string[];
  risk_points?: string[];
  uncertain_items?: string[];
  input_quality?: {
    source_kind: string;
    quality_flags: string[];
    extracted_length: number;
    metadata?: {
      title?: string;
      extractor?: string;
      [key: string]: unknown;
    };
  } | null;
}

export interface RetrievalHit {
  title: string;
  source: string;
  excerpt: string;
  reason: string;
}

export interface WorkflowResult {
  content_breakdown?: string | null;
  review_notes?: string[] | null;
  pending_review_items?: string[] | null;
  evidence_used?: { source: string; title: string }[] | null;
  uncertainties?: string[] | null;
  manual_checks?: string[] | null;
  context_summary?: {
    selected_hit_count: number;
    context_sections: string[];
  } | null;
  processing_trace?: string[] | null;
}

export interface ReviewSnapshot {
  decision: "in_review" | "approved" | "rejected";
  reviewer_note?: string | null;
  rejection_reason?: string | null;
  rerun_reason?: string | null;
  not_adopted_items: string[];
}

export interface ExportJob {
  id: string;
  task_id: string;
  export_type: "markdown" | "structured_text";
  status: "queued" | "exporting" | "completed" | "failed";
  file_path?: string | null;
  error_message?: string | null;
  created_at: string;
  updated_at: string;
}

export interface TaskListItem extends ApiTaskRecord {
  title: string;
}

export interface TaskDetail extends TaskListItem {
  input_content: string;
  understanding_result?: TaskSummary | null;
  retrieval_hits?: RetrievalHit[] | null;
  workflow_result?: WorkflowResult | null;
  review?: ReviewSnapshot | null;
}

export interface TaskCreateInput {
  input_type: TaskInputType;
  content: string;
  knowledge_domain?: string;
}

export interface TaskCreateFormValues {
  inputType: TaskInputType;
  content: string;
  knowledgeDomain?: string;
  file?: File | null;
}

export interface ReviewUpdateInput {
  edited_understanding: UnderstandingResult | null;
  edited_retrieval_hits: ApiRetrievalHit[];
  edited_workflow_result: ApiWorkflowResult | null;
  not_adopted_items: string[];
  reviewer_note?: string | null;
}

export interface ReviewRejectInput {
  rejection_reason: string;
}

export interface ReviewRerunInput {
  rerun_reason: string;
}

export interface ExportJobCreateInput {
  task_id: string;
  export_type: "markdown" | "structured_text";
}

/**
 * The current console slice only exposes inputs that are wired end-to-end in
 * the frontend, including the dedicated multipart upload path for file tasks.
 */
export const TASK_CONSOLE_INPUT_TYPES: TaskInputType[] = ["text", "url", "file"];

const STATUS_META: Record<TaskStatus, TaskStatusMeta> = {
  queued: {
    label: "Queued",
    tone: "info",
    description: "Task is waiting for a worker.",
    isActive: true,
  },
  parsing: {
    label: "Parsing",
    tone: "info",
    description: "Input is being parsed and normalized.",
    isActive: true,
  },
  understanding: {
    label: "Understanding",
    tone: "info",
    description: "Structured understanding is being generated.",
    isActive: true,
  },
  retrieving: {
    label: "Retrieving",
    tone: "info",
    description: "RAG sources are being searched and ranked.",
    isActive: true,
  },
  generating: {
    label: "Generating",
    tone: "info",
    description: "Workflow result is being assembled.",
    isActive: true,
  },
  review_pending: {
    label: "Review pending",
    tone: "warning",
    description: "Automatic processing finished and review is needed.",
    isActive: true,
  },
  reviewing: {
    label: "Reviewing",
    tone: "warning",
    description: "Human review is in progress.",
    isActive: true,
  },
  approved: {
    label: "Approved",
    tone: "success",
    description: "Review passed and the task is ready for export.",
    isActive: false,
  },
  exporting: {
    label: "Exporting",
    tone: "info",
    description: "Reserved for a later review/export slice.",
    isActive: true,
  },
  completed: {
    label: "Completed",
    tone: "success",
    description: "Task finished successfully.",
    isActive: false,
  },
  failed: {
    label: "Failed",
    tone: "danger",
    description: "Task stopped because of an error.",
    isActive: false,
  },
  rejected: {
    label: "Rejected",
    tone: "danger",
    description: "Review rejected the current output and requires regeneration.",
    isActive: false,
  },
};

/**
 * Returns the display metadata for a task status so the UI can stay consistent
 * across task lists, cards, and detail headers.
 */
export function getTaskStatusMeta(status: TaskStatus): TaskStatusMeta {
  return STATUS_META[status];
}

/**
 * Determines whether a task is still active for polling and live refresh logic.
 */
export function isTaskActive(status: TaskStatus): boolean {
  return STATUS_META[status].isActive;
}

/**
 * Produces a compact label for the task source so the UI can show the
 * important part of each submission without dumping raw payloads.
 */
export function summarizeTaskContent(input: Pick<ApiTaskRecord, "input_type"> & { content?: string | null }) {
  if (!input.content) {
    return "No content";
  }

  if (input.input_type === "url") {
    try {
      const parsed = new URL(input.content);
      return parsed.hostname;
    } catch {
      return input.content;
    }
  }

  if (input.input_type === "file") {
    const normalized = input.content.replaceAll("\\", "/");
    return normalized.split("/").filter(Boolean).pop() ?? input.content;
  }

  const trimmed = input.content.trim();
  return trimmed.length > 80 ? `${trimmed.slice(0, 80)}...` : trimmed;
}

/**
 * Derives a stable task card title from the current backend payload without
 * inventing a separate title field before the API owns one.
 */
export function getTaskDisplayTitle(task: Pick<ApiTaskRecord, "input_type" | "content">): string {
  const summary = summarizeTaskContent(task);

  if (task.input_type === "text") {
    return summary === "No content" ? "Text task" : summary;
  }

  if (task.input_type === "url") {
    return summary === "No content" ? "URL task" : summary;
  }

  return summary === "No content" ? "File task" : summary;
}
